name = "beam-lite-worker"
main = "src/worker.ts"
compatibility_date = "2025-09-28"

[vars]
API_VERSION = "v1"

[kv_namespaces]
# Replace with real namespace IDs before deploy
{ binding = "BEAM_KV", id = "<kv-id>" }

[env.staging]
name = "beam-lite-worker-staging"

[env.production]
name = "beam-lite-worker-prod"
